version: 2

defaults: &defaults
  working_directory: ~/go/src/github.com/docker/libnetwork
  docker:
    - image: 'circleci/golang:1.9.6'
      environment:
          CODEPATH: "~/go/src/github.com/docker/libnetwork"

jobs:
  builder:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      #- run: make circle-ci
      - run: make build-builder
      # - run: mkdir -p images
      # - run: echo "libnetwork-builder:$CIRCLE_BUILD_NUM" > images/builder
      # - persist_to_workspace:
      #     root: ~/go
      #     paths:
      #       - src/github.com/docker/libnetwork
  lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      # - attach_workspace:
      #     at: /work/images
      - run:
          environment:
            GOPATH: "$GOPATH:/go/src/github.com/docker/libnetwork"
          command: |
            make circle-ci-check
  cross:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      # - attach_workspace:
      #     at: /work/images
      - run:
          environment:
            GOPATH: "$GOPATH:/go/src/github.com/docker/libnetwork"
          command: |
            make circle-ci-cross
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      # - attach_workspace:
      #     at: /work/images
      - run:
          environment:
            GOPATH: "$GOPATH:/go/src/github.com/docker/libnetwork"
          command: |
            make integration-tests
          # make run-tests


  circleci:
      <<: *defaults
      steps:
        - checkout
        - setup_remote_docker:
            reusable: true
            exclusive: false
        - run:
            environment:
              GOPATH: "$GOPATH:/go/src/github.com/docker/libnetwork"
            command: |
              make circle-ci
workflows:
  version: 2
  ci:
    jobs:
      - builder
      - lint:
         requires:
            - builder
      - cross:
          requires:
             - builder
      - test:
          requires:
             - builder
      - circleci:
          requires:
             - builder
